config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :index
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :show
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update', as: :task
  get 'tasks/:id', to: 'tasks#show'
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
    # @task = Task.find(params[:id])
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to index_path
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.label :completed, "Done!" %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>List of all tasks</h1>

<ul class="tasks"><% @tasks.each do |task| %>
    <li>
      <div class=task>
        <p><% if task.completed %>
          <i class="far fa-check-square"></i>
        <% else %>
          <i class="far fa-square"></i>
        <% end %>
        <%= link_to task.title, show_path(task) %>
        <button class="btn btn-dark"><%= link_to "Delete", delete_task_path(task), method: :delete, data: { confirm: "Are you sure?" } %></button>
      </p>
      </div>
    </li>
  <% end %>
</ul>

<br>

<i class="fas fa-plus"></i><%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1> Add a new task</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<button class="btn btn-light"><%= link_to "Edit this task", edit_path(@task.id) %> </button>

<p>Details: <%= @task.details %></p>
  <p><% if @task.completed %>
      This task is completed.
    <% else %>
      This task is not completed.</p>
  <% end %>

  <br>

<button class="btn btn-success"><%= link_to "Back to all tasks", index_path %></button>